export { default as Home } from "./home/Home.jsx"
export { default as List } from "./list/List.jsx"
export { default as Login } from "./login/Login.jsx"
export { default as New } from "./new/New.jsx"
export { default as Single } from "./single/Single.jsx"
